### ISSUE TITLE
下载下来的漫画有的没加载完

### ISSUE THREAD

**Issue by Linqimao** [lihe07/bilibili-manga-downloader#3]

**Comment by Linqimao** [comment]
每隔二三十页就会有没加载好的图片，显示是灰了一半

**Comment by lihe07** [comment]
感谢反馈！我排查下问题

**Comment by lihe07** [comment]
我在本地没有成功复现这个问题，您能否提供下引发问题的操作和更多信息？

之前的版本确实会出现下载不完整的问题，我已经在[这个commit](https://github.com/lihe07/bilibili-manga-downloader/commit/fb1e57d67bbd1031fcf76e208d95fbd0f5996764)中加入校验。
您可以确认下本地的代码是否为最新版

**Comment by Linqimao** [comment]
感谢大佬！现在已经没有问题了！其实之前搞不好也是我这边的问题，我刚刚试了下挂了回国的梯子（我人在国外）， 下载下来的已经没有问题了。之前可能是网络不好引起的加载问题？

**Comment by lihe07** [comment]
我自己试了下，如果在外国访问确实会出现加载错误。
同时我注意到，B站CDN返回头的"ETag"字段正好是文件的Sha-1校验和！
![图片](https://user-images.githubusercontent.com/53819558/142715390-21672fcd-b8fd-4777-8683-4ccf2892cbf8.png)
![图片](https://user-images.githubusercontent.com/53819558/142715406-4947985b-5ff8-4548-97ea-f444bbc13611.png)
我会在GUI版本和下一次Commit中加入这种校验方式，应该可以有效解决传输的问题。
感谢反馈。
