### ISSUE TITLE
linux下pip install 这个找了半天也没找到是缺的那个依赖

### ISSUE THREAD

**Issue by obhen233** [lihe07/bilibili-manga-downloader#6]
src/qpdf/annotation.cpp:14:46: 致命错误：qpdf/QPDFAnnotationObjectHelper.hh：没有那个文件或目录
     #include <qpdf/QPDFAnnotationObjectHelper.hh>
                                                  ^
    编译中断。

**Comment by lihe07** [comment]
看输出可能是QPDF？

**Comment by obhen233** [comment]
QPDF也装了，我看了，不过我抄你的抄了一份https://github.com/obhen233/BilibiliComic

**Comment by lihe07** [comment]
Java实属是盲区了，我最近在用Rust复写，顺便做个GUI。
Rust话，编译之后应该不会出现依赖问题

**Comment by obhen233** [comment]
你加油

**Comment by obhen233** [comment]
python的还解决不，不解决我就关了
